### ISSUE TITLE
Question about Training with SPair Data

### ISSUE THREAD

**Issue by SYL-322** [VICO-UoE/SphericalMaps#2]
Hi,

Thanks for your insightful work! 
I have a question about a part of the code in datasets/SPair.py,

<img width="490" alt="image" src="https://github.com/user-attachments/assets/7f3f2aef-b733-49bd-a08e-69c615f1b547">

It seems that you are only using one pair per object instance for training instead of the original training pair setting. If I understand it correctly, why not use all the training pairs?

**Comment by omariott** [comment]
Hello,

Our training protocol does not make use of pairs, instead, each object instance is individually compared to the spherical prototype. So, as you noted, we filter out the training set and only keep one "pair" per instance.
Later on in the `__getitem__` function, only the source image of the 'pair' is returned:
https://github.com/VICO-UoE/SphericalMaps/blob/f74fd57e0fbe2f0194b1c92203839e436c89078a/datasets/SPair.py#L177

Hope this helps!

**Comment by SYL-322** [comment]
Thank you very much for your explanation! I misunderstood your training protocol and now I am clear
